name: Trivy Scan
on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the repository to scan'
        required: true
        default: 'terraform-aws-infrastructure'

jobs:
  trivy-scan:
    permissions:
      contents: read
      security-events: write
      issues: write
      id-token: write
      pull-requests: write
    uses: Nimesha-Premaraja/common-workflows/.github/workflows/trivy.yaml@patch-2
